language: rust
rust:
  - stable
  - beta
  - nightly

script:
  - cargo build
  - cargo test
  - cargo doc

cache: cargo
matrix:
  fast_finish: true
  include:
    - rust: nightly-2018-05-06
      env: # use env so updating versions causes cache invalidation
        - CLIPPY_VERSION=0.0.197
      before_script:
        - rustup component add rustfmt-preview
        - cargo install clippy --version $CLIPPY_VERSION || echo "clippy already installed"
      script:
        - cargo fmt -- --write-mode=check
        - cargo clippy
